'use client';
import{useState,useEffect,useRef}from'react';
import{createClient}from'@supabase/supabase-js';
export const sb=createClient('https://ammymxsyerlkdezsxuip.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbXlteHN5ZXJsa2RlenN4dWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwOTI0NzMsImV4cCI6MjA4OTY2ODQ3M30.kS0xKDTl3KyjWBCB4Tp-8WdWPkAqXC62djKg4VPgC6E');
export const STORAGE_URL='https://ammymxsyerlkdezsxuip.supabase.co/storage/v1/object/public/academy-uploads/';
export const CC:Record<string,string>={'Budgeting':'#1a6bff','Investing':'#10b981','Debt':'#ef4444','Freelance':'#f59e0b','Tax':'#8b5cf6','Crypto':'#06b6d4','Business':'#f97316','Savings':'#3b82f6','Default':'#6c2ef5'};
export const CI:Record<string,string>={'Budgeting':'💰','Investing':'📈','Debt':'🏦','Freelance':'💼','Tax':'🧾','Crypto':'⛓','Business':'🏢','Savings':'🐷','Default':'📚'};
export const gc=(c:string)=>CC[c]||CC.Default;
export const gi=(c:string)=>CI[c]||CI.Default;
export function WaveLogo({size=32}:{size?:number}){return(<svg width={size} height={size} viewBox="0 0 64 64"><defs><linearGradient id="wga" x1="0%" y1="100%" x2="100%" y2="0%"><stop offset="0%" stopColor="#1a6bff"/><stop offset="60%" stopColor="#6c2ef5"/><stop offset="100%" stopColor="#0d9aff"/></linearGradient></defs><rect width="64" height="64" rx="16" fill="url(#wga)"/><path d="M10 38 Q18 22 26 32 Q34 42 42 26 Q50 10 54 26" stroke="white" strokeWidth="5" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>);}
export const B:Record<string,any>={wrap:{minHeight:'100vh',background:'#000814',color:'#e2e8f0',fontFamily:"'Inter',sans-serif"},hdr:{background:'#0a1628',padding:'16px 24px',borderBottom:'1px solid rgba(255,255,255,0.06)',display:'flex',alignItems:'center',gap:12},title:{fontSize:22,fontWeight:800,fontFamily:"'Orbitron',monospace",background:'linear-gradient(135deg,#1a6bff,#6c2ef5)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',margin:0},tabs:{display:'flex',gap:6,padding:'12px 24px',borderBottom:'1px solid rgba(255,255,255,0.06)',overflowX:'auto'},tab:(a:boolean)=>({padding:'8px 18px',borderRadius:8,border:'none',cursor:'pointer',fontWeight:600,fontSize:13,background:a?'linear-gradient(135deg,#1a6bff,#6c2ef5)':'rgba(255,255,255,0.04)',color:a?'#fff':'#64748b',whiteSpace:'nowrap',flexShrink:0}),grid:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:16,padding:'16px 24px 80px'},card:{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:14,overflow:'hidden',cursor:'pointer'},badge:(c:string)=>({display:'inline-block',padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,background:`${c}22`,color:c}),btn:(v:string)=>({padding:'10px 20px',borderRadius:8,border:'none',cursor:'pointer',fontWeight:700,fontSize:13,background:v==='primary'?'linear-gradient(135deg,#1a6bff,#6c2ef5)':v==='danger'?'rgba(239,68,68,0.15)':'rgba(255,255,255,0.06)',color:v==='danger'?'#ef4444':'#fff'}),inp:{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:8,padding:'10px 14px',color:'#e2e8f0',fontSize:14,outline:'none',width:'100%',boxSizing:'border-box'},ta:{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:8,padding:'10px 14px',color:'#e2e8f0',fontSize:14,outline:'none',width:'100%',boxSizing:'border-box',resize:'vertical',minHeight:100},label:{fontSize:12,color:'#64748b',fontWeight:600,marginBottom:6,display:'block'},toast:{position:'fixed',bottom:24,left:'50%',transform:'translateX(-50%)',background:'#1a6bff',color:'#fff',padding:'12px 24px',borderRadius:10,fontWeight:600,fontSize:14,zIndex:9999,pointerEvents:'none',maxWidth:'90vw',textAlign:'center'},back:{background:'none',border:'none',color:'#1a6bff',cursor:'pointer',fontSize:14,fontWeight:600,display:'flex',alignItems:'center',gap:6,padding:'0 0 16px'},};
export async function doUpload(file:File,folder:string,uid:string,onProgress?:(p:number)=>void):Promise<string|null>{
  const ext=file.name.split('.').pop()?.toLowerCase()||'bin';
  const ts=Date.now();const rand=Math.random().toString(36).slice(2,8);
  const path=uid+'/'+folder+'/'+ts+'_'+rand+'.'+ext;
  try{
    if(onProgress)onProgress(10);
    const{data,error}=await sb.storage.from('academy-uploads').upload(path,file,{cacheControl:'3600',upsert:true,contentType:file.type||'application/octet-stream'});
    if(error){console.error('Upload err:',error.message,error);return null;}
    if(onProgress)onProgress(100);
    const{data:u}=sb.storage.from('academy-uploads').getPublicUrl(path);
    return u.publicUrl;
  }catch(e:any){console.error('Upload exception:',e?.message||e);return null;}
}
export function UploadField({label,accept,value,onUrl,uid,folder,type='file'}:{label:string,accept:string,value:string,onUrl:(u:string)=>void,uid:string,folder:string,type?:string}){
  const ref=useRef<HTMLInputElement>(null);
  const[prog,setProg]=useState(0);const[uploading,setUploading]=useState(false);const[err,setErr]=useState('');const[done,setDone]=useState(false);
  async function handle(f:File){setUploading(true);setProg(10);setErr('');setDone(false);const url=await doUpload(f,folder,uid,p=>setProg(p));setUploading(false);if(url){onUrl(url);setProg(100);setDone(true);}else{setErr('Upload failed — check browser console');}}
  return(<div style={{marginBottom:14}}>{label&&<label style={B.label}>{label}</label>}<div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',marginBottom:6}}><input ref={ref} type="file" accept={accept} style={{display:'none'}} onChange={e=>{const f=e.target.files?.[0];if(f)handle(f);e.target.value='';}}/>
    <button type="button" disabled={uploading} onClick={()=>ref.current?.click()} style={{padding:'8px 16px',borderRadius:8,border:'1px dashed rgba(26,107,255,0.5)',background:'rgba(26,107,255,0.08)',color:'#1a6bff',cursor:uploading?'not-allowed':'pointer',fontSize:13,fontWeight:600,opacity:uploading?0.7:1,flexShrink:0}}>{uploading?`Uploading ${prog}%`:done?'✓ Uploaded':`📤 Upload ${type==='video'?'Video':type==='image'?'Image':'File'}`}</button>
    {type!=='video'&&<><span style={{color:'#475569',fontSize:12}}>or URL:</span><input style={{...B.inp,flex:1,minWidth:160}} placeholder="https://..." value={value} onChange={e=>{onUrl(e.target.value);setDone(false);}} disabled={uploading}/></>}
  </div>{uploading&&<div style={{height:4,background:'rgba(255,255,255,0.08)',borderRadius:2,marginBottom:6}}><div style={{height:'100%',width:`${prog}%`,background:'linear-gradient(90deg,#1a6bff,#6c2ef5)',borderRadius:2,transition:'width 0.3s'}}/></div>}
  {err&&<div style={{fontSize:11,color:'#ef4444',marginBottom:4}}>{err}</div>}{done&&<div style={{fontSize:11,color:'#10b981',marginBottom:4}}>✓ Uploaded successfully</div>}
  {value&&!uploading&&type==='image'&&<img src={value} alt="" style={{height:80,borderRadius:8,objectFit:'cover',marginTop:4}}/>}
  {value&&!uploading&&type==='video'&&<div style={{fontSize:11,color:'#10b981',marginTop:4}}>✓ {value.split('/').pop()?.slice(0,50)}</div>}</div>);}
export function UploadBtn({label,accept,onFile,uploading}:{label:string,accept:string,onFile:(f:File)=>void,uploading:boolean}){const ref=useRef<HTMLInputElement>(null);return(<><input ref={ref} type="file" accept={accept} style={{display:'none'}} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f);e.target.value='';}}/>
  <button type="button" disabled={uploading} onClick={()=>ref.current?.click()} style={{padding:'8px 16px',borderRadius:8,border:'1px dashed rgba(26,107,255,0.5)',background:'rgba(26,107,255,0.08)',color:'#1a6bff',cursor:uploading?'not-allowed':'pointer',fontSize:13,fontWeight:600,opacity:uploading?0.7:1}}>{uploading?'Uploading...':label}</button></>);}
export function ArticleDetail({article,user,onBack}:{article:any,user:any,onBack:()=>void}){const[liked,setLiked]=useState(false);const[likes,setLikes]=useState(article.likes||0);useEffect(()=>{sb.from('academy_articles').update({views:(article.views||0)+1}).eq('id',article.id);if(user)sb.from('academy_article_likes').select('*').eq('user_id',user.id).eq('article_id',article.id).then(({data})=>setLiked((data||[]).length>0));},[]);
  async function toggleLike(){if(!user)return;if(liked){await sb.from('academy_article_likes').delete().eq('user_id',user.id).eq('article_id',article.id);await sb.from('academy_articles').update({likes:likes-1}).eq('id',article.id);setLikes((l:number)=>l-1);setLiked(false);}else{await sb.from('academy_article_likes').insert({user_id:user.id,article_id:article.id});await sb.from('academy_articles').update({likes:likes+1}).eq('id',article.id);setLikes((l:number)=>l+1);setLiked(true);}}
  return(<div style={{...B.wrap,paddingBottom:80}}><div style={{maxWidth:760,margin:'0 auto',padding:'24px'}}><button style={B.back} onClick={onBack}>← Back</button>{article.cover_url&&<img src={article.cover_url} alt="" style={{width:'100%',height:240,objectFit:'cover',borderRadius:12,marginBottom:20}}/>}<div style={{display:'flex',gap:8,marginBottom:12,flexWrap:'wrap'}}><span style={B.badge(gc(article.category))}>{article.category}</span>{(article.tags||[]).map((t:string)=><span key={t} style={{...B.badge('#475569'),marginLeft:2}}>{t}</span>)}</div><h1 style={{fontSize:28,fontWeight:800,lineHeight:1.3,marginBottom:16,color:'#f1f5f9'}}>{article.title}</h1><div style={{display:'flex',alignItems:'center',gap:16,marginBottom:24,paddingBottom:20,borderBottom:'1px solid rgba(255,255,255,0.06)'}}><div style={{width:40,height:40,borderRadius:'50%',background:'linear-gradient(135deg,#1a6bff,#6c2ef5)',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:700,fontSize:16,flexShrink:0}}>{(article.author_name||'?')[0].toUpperCase()}</div><div><div style={{fontWeight:700,color:'#e2e8f0'}}>{article.author_name}</div><div style={{fontSize:12,color:'#64748b'}}>{new Date(article.created_at).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}{article.read_time?` · ${article.read_time} min read`:''}</div></div><div style={{marginLeft:'auto',display:'flex',gap:16,alignItems:'center'}}><span style={{fontSize:13,color:'#64748b'}}>👁 {article.views||0}</span><button onClick={toggleLike} style={{background:'none',border:'none',cursor:user?'pointer':'default',display:'flex',alignItems:'center',gap:4,fontSize:13}}><span style={{fontSize:20,color:liked?'#ef4444':'#64748b'}}>{liked?'❤️':'🤍'}</span><span style={{color:'#64748b'}}>{likes}</span></button></div></div><div style={{fontSize:16,lineHeight:1.9,color:'#cbd5e1',whiteSpace:'pre-wrap'}}>{article.content}</div></div></div>);}
export function BookReader({book,onBack}:{book:any,onBack:()=>void}){const url=book.file_url||(book.file_path?STORAGE_URL+book.file_path:null);return(<div style={{...B.wrap,display:'flex',flexDirection:'column',height:'100vh'}}><div style={B.hdr}><button style={{...B.back,padding:0}} onClick={onBack}>← Back</button><h2 style={{...B.title,fontSize:16,margin:0}}>{book.title}</h2>{url&&<a href={url} download style={{...B.btn('ghost'),marginLeft:'auto',textDecoration:'none',fontSize:12,padding:'6px 14px'}}>Download</a>}</div>{url?<iframe src={url} style={{flex:1,border:'none',background:'#fff'}} title={book.title}/>:<div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',color:'#475569'}}><div style={{fontSize:48,marginBottom:12}}>📖</div><div>No file yet</div></div>}</div>);}
export function LessonViewer({course,lessons,activeLesson,setActiveLesson,user,onBack,onComplete}:{course:any,lessons:any[],activeLesson:any,setActiveLesson:any,user:any,onBack:()=>void,onComplete:(l:any)=>void}){
  const[qa,setQa]=useState<Record<number,number>>({});const[qResult,setQResult]=useState('');const progress=course.progress||0;const ltype=(l:any)=>l.lesson_type||'text';
  function submitQuiz(l:any){const qs=l.questions||[];let correct=0;qs.forEach((q:any,i:number)=>{if(qa[i]===q.correct_index)correct++;});const pct=Math.round((correct/qs.length)*100);setQResult(`${correct}/${qs.length} correct (${pct}%)${pct>=70?' — Passed! ✓':' — Try again'}`);if(pct>=70)onComplete(l);}
  const videoSrc=(l:any)=>{const u=l.video_url||'';if(!u)return null;if(u.includes('youtube.com')||u.includes('youtu.be'))return u.replace('watch?v=','embed/').replace('youtu.be/','www.youtube.com/embed/');return u;};
  return(<div style={{...B.wrap,display:'flex',flexDirection:'column',height:'100vh'}}><div style={{background:'#0a1628',padding:'10px 20px',borderBottom:'1px solid rgba(255,255,255,0.06)',display:'flex',alignItems:'center',gap:12,flexShrink:0}}><button style={{...B.back,padding:0}} onClick={onBack}>← Exit</button><div style={{flex:1}}><div style={{fontSize:14,fontWeight:700,color:'#e2e8f0'}}>{course.title}</div><div style={{fontSize:11,color:'#64748b'}}>{progress}% complete</div></div><div style={{width:100,height:4,background:'rgba(255,255,255,0.08)',borderRadius:2,flexShrink:0}}><div style={{height:'100%',width:`${progress}%`,background:'linear-gradient(90deg,#1a6bff,#6c2ef5)',borderRadius:2,transition:'width 0.5s'}}/></div></div>
  <div style={{display:'flex',flex:1,overflow:'hidden'}}><div style={{width:240,background:'rgba(255,255,255,0.02)',borderRight:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0}}><div style={{padding:'10px 14px',fontSize:11,fontWeight:700,color:'#475569',textTransform:'uppercase',letterSpacing:'0.08em'}}>Lessons ({lessons.length})</div>
  {lessons.map((l:any,i:number)=>{const done=progress>=(((i+1)/lessons.length)*100);const active=activeLesson?.id===l.id;return(<div key={l.id} onClick={()=>{setActiveLesson(l);setQa({});setQResult('');}} style={{padding:'10px 14px',cursor:'pointer',borderLeft:`3px solid ${active?'#1a6bff':'transparent'}`,background:active?'rgba(26,107,255,0.08)':'transparent',display:'flex',alignItems:'center',gap:8}}><span style={{width:20,height:20,borderRadius:'50%',background:done?'#10b981':active?'#1a6bff':'rgba(255,255,255,0.08)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:9,color:'#fff',flexShrink:0,fontWeight:700}}>{done?'✓':i+1}</span><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,color:active?'#1a6bff':'#94a3b8',lineHeight:1.3,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{l.title}</div><div style={{fontSize:10,color:'#475569',marginTop:1}}>{ltype(l)==='video'?'▶ Video':ltype(l)==='quiz'?'📝 Quiz':'📄 Reading'}</div></div></div>);})}
  </div><div style={{flex:1,overflowY:'auto',padding:24}}>{activeLesson?(<><h2 style={{fontSize:20,fontWeight:800,marginBottom:16,color:'#f1f5f9'}}>{activeLesson.title}</h2>
  {ltype(activeLesson)==='video'&&(()=>{const src=videoSrc(activeLesson);return(<div style={{width:'100%',aspectRatio:'16/9',background:'rgba(0,0,0,0.5)',borderRadius:12,overflow:'hidden',marginBottom:20,border:'1px solid rgba(255,255,255,0.08)'}}>{src?(src.includes('youtube.com/embed')?<iframe width="100%" height="100%" src={src} style={{border:'none'}} allowFullScreen/>:<video src={src} controls style={{width:'100%',height:'100%',background:'#000'}} controlsList="nodownload"/>):(<div style={{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',height:'100%',color:'#475569'}}><div style={{fontSize:48}}>▶</div><div style={{fontSize:13,marginTop:8}}>No video</div></div>)}</div>);})()}
  {ltype(activeLesson)==='quiz'&&(<div style={{background:'rgba(139,92,246,0.05)',border:'1px solid rgba(139,92,246,0.15)',borderRadius:12,padding:20,marginBottom:16}}><div style={{fontWeight:800,fontSize:15,color:'#8b5cf6',marginBottom:14}}>Quiz</div>{(activeLesson.questions||[]).map((q:any,qi:number)=>(<div key={qi} style={{marginBottom:18}}><div style={{fontWeight:600,marginBottom:8,color:'#e2e8f0'}}>{qi+1}. {q.question}</div>{(q.options||[]).map((opt:string,oi:number)=>(<div key={oi} onClick={()=>setQa(p=>({...p,[qi]:oi}))} style={{padding:'9px 14px',borderRadius:8,marginBottom:5,cursor:'pointer',background:qa[qi]===oi?'rgba(26,107,255,0.2)':'rgba(255,255,255,0.03)',border:`1px solid ${qa[qi]===oi?'#1a6bff':'rgba(255,255,255,0.07)'}`,fontSize:14,color:qa[qi]===oi?'#e2e8f0':'#94a3b8'}}>{opt}</div>))}</div>))}{qResult&&<div style={{padding:'10px 14px',borderRadius:8,background:qResult.includes('Passed')?'rgba(16,185,129,0.1)':'rgba(239,68,68,0.1)',color:qResult.includes('Passed')?'#10b981':'#ef4444',fontWeight:700,marginBottom:10}}>{qResult}</div>}<button style={B.btn('primary')} onClick={()=>submitQuiz(activeLesson)}>Submit Quiz</button></div>)}
  {activeLesson.content&&<div style={{fontSize:15,lineHeight:1.9,color:'#cbd5e1',whiteSpace:'pre-wrap',marginBottom:20}}>{activeLesson.content}</div>}
  {ltype(activeLesson)!=='quiz'&&<button style={{...B.btn('primary'),width:'100%',padding:'13px'}} onClick={()=>onComplete(activeLesson)}>{lessons.indexOf(activeLesson)===lessons.length-1?'Complete Course 🎉':'Next Lesson →'}</button>}</>):(<div style={{textAlign:'center',padding:60,color:'#475569'}}><div style={{fontSize:44,marginBottom:12}}>📖</div><div>Select a lesson</div></div>)}</div></div></div>);}
export function CreatorStudio({user,profile,onBack,showToast}:{user:any,profile:any,onBack:()=>void,showToast:(m:string)=>void}){
  const[tab,setTab]=useState<'dashboard'|'new-course'|'edit-course'|'profile'>('dashboard');const[myCourses,setMyCourses]=useState<any[]>([]);const[editingCourse,setEditingCourse]=useState<any>(null);const[saving,setSaving]=useState(false);
  const[ep,setEp]=useState({display_name:profile?.display_name||user?.email?.split('@')[0]||'',bio:profile?.bio||'',website:profile?.website||'',expertise:(profile?.expertise||[]).join(', ')});
  const blankCourse=()=>({title:'',description:'',category:'Budgeting',level:'Beginner',price:'0',is_free:true,language:'English',what_you_learn:'',requirements:'',thumbnail_url:''});
  const[nc,setNc]=useState<any>(blankCourse());const[ls,setLs]=useState<any[]>([{title:'Introduction',lesson_type:'text',content:'',video_url:'',is_free_preview:true}]);const[stats,setStats]=useState({courses:0,students:0,lessons:0});
  useEffect(()=>{if(user)loadDashboard();},[user]);
  async function loadDashboard(){const{data:courses}=await sb.from('academy_courses').select('id,title,category,level,is_free,price,is_published,total_enrollments,avg_rating,thumbnail_url,created_at').eq('instructor_id',user.id).order('created_at',{ascending:false});setMyCourses(courses||[]);const totalStudents=(courses||[]).reduce((s:number,c:any)=>s+(c.total_enrollments||0),0);let lessonCount=0;if((courses||[]).length>0){const ids=(courses||[]).map((c:any)=>c.id);const{count}=await sb.from('academy_lessons').select('id',{count:'exact',head:true}).in('course_id',ids);lessonCount=count||0;}setStats({courses:(courses||[]).length,students:totalStudents,lessons:lessonCount});}
  async function loadCourseForEdit(course:any){const{data:lessons}=await sb.from('academy_lessons').select('*').eq('course_id',course.id).order('order_index');setEditingCourse(course);setNc({...course,price:String(course.price||0),what_you_learn:(course.what_you_learn||[]).join('\n'),requirements:(course.requirements||[]).join('\n')});setLs(lessons&&lessons.length>0?lessons:[{title:'Introduction',lesson_type:'text',content:'',video_url:'',is_free_preview:true}]);setTab('edit-course');}
  async function saveProfile(){setSaving(true);const{error}=await sb.from('academy_creator_profiles').upsert({user_id:user.id,...ep,expertise:ep.expertise.split(',').map((s:string)=>s.trim()).filter(Boolean)},{onConflict:'user_id'});if(error)showToast('Error: '+error.message);else showToast('Profile saved!');setSaving(false);}
  async function saveCourse(publish:boolean){if(!nc.title.trim()){showToast('Course title required');return;}setSaving(true);const payload={title:nc.title.trim(),description:nc.description,category:nc.category,level:nc.level,language:nc.language||'English',thumbnail_url:nc.thumbnail_url||null,price:parseFloat(nc.price)||0,is_free:parseFloat(nc.price)===0,what_you_learn:nc.what_you_learn.split('\n').filter((s:string)=>s.trim()),requirements:nc.requirements.split('\n').filter((s:string)=>s.trim()),instructor_id:user.id,instructor_name:ep.display_name||user.email?.split('@')[0]||'Instructor',is_published:publish,certificate_enabled:true};let courseId=editingCourse?.id;
    if(courseId){const{error}=await sb.from('academy_courses').update(payload).eq('id',courseId);if(error){showToast('Error: '+error.message);setSaving(false);return;}}else{const{data,error}=await sb.from('academy_courses').insert(payload).select('id').single();if(error){showToast('Error: '+error.message);setSaving(false);return;}courseId=data.id;}
    const validLessons=ls.filter((l:any)=>l.title.trim());if(validLessons.length>0){if(editingCourse){await sb.from('academy_lessons').delete().eq('course_id',courseId);}const rows=validLessons.map((l:any,i:number)=>({course_id:courseId,title:l.title.trim(),lesson_type:l.lesson_type||'text',content:l.content||'',video_url:l.video_url||null,order_index:i,is_free_preview:l.is_free_preview||false,questions:l.questions||null}));const{error:lErr}=await sb.from('academy_lessons').insert(rows);if(lErr){showToast('Lessons error: '+lErr.message);setSaving(false);return;}}
    await sb.from('academy_courses').update({total_lessons:validLessons.length}).eq('id',courseId);showToast(publish?'Course published! 🎉':'Saved as draft');setSaving(false);setTab('dashboard');setNc(blankCourse());setLs([{title:'Introduction',lesson_type:'text',content:'',video_url:'',is_free_preview:true}]);setEditingCourse(null);loadDashboard();}
  async function deleteCourse(id:string){if(!confirm('Delete this course?'))return;await sb.from('academy_lessons').delete().eq('course_id',id);await sb.from('academy_courses').delete().eq('id',id);showToast('Deleted');loadDashboard();}
  async function togglePublish(course:any){await sb.from('academy_courses').update({is_published:!course.is_published}).eq('id',course.id);showToast(course.is_published?'Unpublished':'Published!');loadDashboard();}
  const cats=['Budgeting','Investing','Debt','Freelance','Tax','Crypto','Business','Savings'];const isEditing=tab==='edit-course'||tab==='new-course';
  return(<div style={{...B.wrap,paddingBottom:80}}><div style={{...B.hdr,flexWrap:'wrap',gap:8}}><button style={{...B.back,padding:0}} onClick={isEditing?(()=>setTab('dashboard')):onBack}>← {isEditing?'Back':'Exit Studio'}</button><h2 style={{...B.title,fontSize:18,margin:0}}>Creator Studio</h2>{!isEditing&&<div style={{marginLeft:'auto',display:'flex',gap:8}}><button style={{...B.btn('primary'),padding:'7px 16px',fontSize:12}} onClick={()=>{setNc(blankCourse());setLs([{title:'Introduction',lesson_type:'text',content:'',video_url:'',is_free_preview:true}]);setEditingCourse(null);setTab('new-course');}}>+ New Course</button></div>}</div>
  {!isEditing&&<div style={B.tabs}>{(['dashboard','profile']as const).map(t=><button key={t} style={B.tab(tab===t)} onClick={()=>setTab(t)}>{t==='dashboard'?'My Courses':'Profile'}</button>)}</div>}
  <div style={{padding:'20px 24px'}}>
  {tab==='profile'&&(<div style={{maxWidth:520}}><h3 style={{color:'#e2e8f0',marginBottom:16,fontWeight:800}}>Creator Profile</h3><div style={{marginBottom:14}}><label style={B.label}>Display Name</label><input style={B.inp} value={ep.display_name} onChange={e=>setEp(p=>({...p,display_name:e.target.value}))}/></div><div style={{marginBottom:14}}><label style={B.label}>Bio</label><textarea style={B.ta} rows={3} value={ep.bio} onChange={e=>setEp(p=>({...p,bio:e.target.value}))}/></div><div style={{marginBottom:14}}><label style={B.label}>Website</label><input style={B.inp} value={ep.website} onChange={e=>setEp(p=>({...p,website:e.target.value}))}/></div><div style={{marginBottom:20}}><label style={B.label}>Expertise (comma separated)</label><input style={B.inp} placeholder="e.g. Budgeting, Investing" value={ep.expertise} onChange={e=>setEp(p=>({...p,expertise:e.target.value}))}/></div><button style={B.btn('primary')} onClick={saveProfile} disabled={saving}>{saving?'Saving...':'Save Profile'}</button></div>)}
  {tab==='dashboard'&&(<><div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{[['Courses',stats.courses,'#1a6bff'],['Students',stats.students,'#10b981'],['Lessons',stats.lessons,'#8b5cf6']].map(([l,v,c])=>(<div key={l as string} style={{background:'rgba(255,255,255,0.03)',border:`1px solid ${c}33`,borderRadius:12,padding:'14px 20px',minWidth:120,flex:1}}><div style={{fontSize:28,fontWeight:800,fontFamily:"'Orbitron',monospace",color:c as string}}>{v}</div><div style={{fontSize:12,color:'#64748b',marginTop:2}}>{l}</div></div>))}</div>
  {myCourses.length===0?(<div style={{textAlign:'center',padding:40,color:'#475569',background:'rgba(255,255,255,0.02)',borderRadius:12,border:'1px dashed rgba(255,255,255,0.08)'}}><div style={{fontSize:40,marginBottom:12}}>🎬</div><div style={{marginBottom:16}}>No courses yet</div><button style={B.btn('primary')} onClick={()=>{setNc(blankCourse());setLs([{title:'Introduction',lesson_type:'text',content:'',video_url:'',is_free_preview:true}]);setEditingCourse(null);setTab('new-course');}}>Create Course</button></div>):(
  <div style={{display:'grid',gap:12}}>{myCourses.map((c:any)=>(<div key={c.id} style={{background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:12,padding:16,display:'flex',gap:14,alignItems:'center',flexWrap:'wrap'}}><div style={{width:48,height:48,borderRadius:10,background:c.thumbnail_url?'transparent':`${gc(c.category)}22`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:22,flexShrink:0,overflow:'hidden'}}>{c.thumbnail_url?<img src={c.thumbnail_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:gi(c.category)}</div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:700,color:'#e2e8f0',fontSize:14,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{c.title}</div><div style={{fontSize:12,color:'#64748b',marginTop:3,display:'flex',gap:10,flexWrap:'wrap'}}><span style={B.badge(gc(c.category))}>{c.category}</span><span>{c.level}</span><span style={{color:c.is_free?'#10b981':'#e2e8f0'}}>{c.is_free?'Free':'$'+c.price}</span><span>👥 {c.total_enrollments||0}</span>{c.avg_rating>0&&<span style={{color:'#f59e0b'}}>★ {c.avg_rating}</span>}</div></div><div style={{display:'flex',gap:6,flexShrink:0,flexWrap:'wrap'}}><span style={{...B.badge(c.is_published?'#10b981':'#f59e0b'),padding:'4px 10px',fontSize:11}}>{c.is_published?'Live':'Draft'}</span><button style={{...B.btn('ghost'),padding:'5px 12px',fontSize:11}} onClick={()=>loadCourseForEdit(c)}>Edit</button><button style={{...B.btn('ghost'),padding:'5px 12px',fontSize:11}} onClick={()=>togglePublish(c)}>{c.is_published?'Unpublish':'Publish'}</button><button style={{...B.btn('danger'),padding:'5px 12px',fontSize:11}} onClick={()=>deleteCourse(c.id)}>Delete</button></div></div>))}</div>)}</>)}
  {isEditing&&(<div style={{maxWidth:760}}><h3 style={{color:'#e2e8f0',marginBottom:20,fontWeight:800,fontSize:18}}>{editingCourse?'Edit Course':'New Course'}</h3>
  <UploadField label="Thumbnail" accept="image/jpeg,image/png,image/webp" value={nc.thumbnail_url||''} onUrl={u=>setNc((p:any)=>({...p,thumbnail_url:u}))} uid={user.id} folder="thumbnails" type="image"/>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginBottom:14}}><div style={{gridColumn:'1/-1'}}><label style={B.label}>Course Title *</label><input style={B.inp} placeholder="e.g. Budgeting for Beginners" value={nc.title} onChange={e=>setNc((p:any)=>({...p,title:e.target.value}))}/></div><div><label style={B.label}>Category</label><select style={B.inp} value={nc.category} onChange={e=>setNc((p:any)=>({...p,category:e.target.value}))}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div><label style={B.label}>Level</label><select style={B.inp} value={nc.level} onChange={e=>setNc((p:any)=>({...p,level:e.target.value}))}>{['Beginner','Intermediate','Advanced'].map(l=><option key={l}>{l}</option>)}</select></div><div><label style={B.label}>Price (0 = free)</label><input style={B.inp} type="number" min="0" step="0.01" value={nc.price} onChange={e=>setNc((p:any)=>({...p,price:e.target.value}))}/></div><div><label style={B.label}>Language</label><select style={B.inp} value={nc.language||'English'} onChange={e=>setNc((p:any)=>({...p,language:e.target.value}))}>{['English','Pashto','Dari','Arabic','Urdu','German','French','Spanish'].map(l=><option key={l}>{l}</option>)}</select></div></div>
  <div style={{marginBottom:14}}><label style={B.label}>Description</label><textarea style={{...B.ta,minHeight:80}} value={nc.description} onChange={e=>setNc((p:any)=>({...p,description:e.target.value}))}/></div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginBottom:20}}><div><label style={B.label}>What students learn (one per line)</label><textarea style={B.ta} rows={4} value={nc.what_you_learn} onChange={e=>setNc((p:any)=>({...p,what_you_learn:e.target.value}))}/></div><div><label style={B.label}>Requirements (one per line)</label><textarea style={B.ta} rows={4} value={nc.requirements} onChange={e=>setNc((p:any)=>({...p,requirements:e.target.value}))}/></div></div>
  <div style={{borderTop:'1px solid rgba(255,255,255,0.06)',paddingTop:20,marginBottom:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><h4 style={{color:'#e2e8f0',margin:0,fontWeight:800}}>Lessons ({ls.length})</h4><div style={{display:'flex',gap:8}}>{(['text','video','quiz']as const).map(t=>(<button key={t} style={{...B.btn('ghost'),padding:'5px 12px',fontSize:11}} onClick={()=>setLs(p=>[...p,{title:'',lesson_type:t,content:'',video_url:'',is_free_preview:false}])}>+ {t==='video'?'Video':t==='quiz'?'Quiz':'Reading'}</button>))}</div></div>
  {ls.map((l:any,i:number)=>(<div key={i} style={{background:'rgba(255,255,255,0.02)',border:'1px solid rgba(255,255,255,0.07)',borderRadius:12,padding:16,marginBottom:10}}><div style={{display:'flex',gap:8,marginBottom:10,alignItems:'center'}}><div style={{width:28,height:28,borderRadius:'50%',background:l.lesson_type==='video'?'rgba(26,107,255,0.2)':l.lesson_type==='quiz'?'rgba(139,92,246,0.2)':'rgba(16,185,129,0.2)',color:l.lesson_type==='video'?'#1a6bff':l.lesson_type==='quiz'?'#8b5cf6':'#10b981',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,flexShrink:0,fontWeight:700}}>{l.lesson_type==='video'?'▶':l.lesson_type==='quiz'?'?':'T'}</div><input style={{...B.inp,flex:1}} placeholder={`Lesson ${i+1} title`} value={l.title} onChange={e=>setLs(p=>p.map((x:any,j:number)=>j===i?{...x,title:e.target.value}:x))}/><select style={{...B.inp,width:'auto'}} value={l.lesson_type} onChange={e=>setLs(p=>p.map((x:any,j:number)=>j===i?{...x,lesson_type:e.target.value}:x))}><option value="text">📄 Reading</option><option value="video">▶ Video</option><option value="quiz">📝 Quiz</option></select><label style={{display:'flex',alignItems:'center',gap:5,fontSize:11,color:'#64748b',cursor:'pointer',flexShrink:0,whiteSpace:'nowrap'}}><input type="checkbox" checked={l.is_free_preview||false} onChange={e=>setLs(p=>p.map((x:any,j:number)=>j===i?{...x,is_free_preview:e.target.checked}:x))}/>Free</label><button onClick={()=>setLs(p=>p.filter((_:any,j:number)=>j!==i))} style={{background:'none',border:'none',color:'#ef4444',cursor:'pointer',fontSize:16,flexShrink:0,padding:0}}>✕</button></div>
  {l.lesson_type==='video'&&(<UploadField label="" accept="video/mp4,video/webm,video/quicktime,video/x-m4v" value={l.video_url||''} onUrl={u=>setLs(p=>p.map((x:any,j:number)=>j===i?{...x,video_url:u}:x))} uid={user.id} folder="videos" type="video"/>)}
  <textarea style={{...B.ta,minHeight:l.lesson_type==='quiz'?52:80}} placeholder={l.lesson_type==='quiz'?'Quiz intro (optional)':'Lesson notes or reading content'} value={l.content||''} onChange={e=>setLs(p=>p.map((x:any,j:number)=>j===i?{...x,content:e.target.value}:x))}/></div>))}</div>
  <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button style={{...B.btn('primary'),padding:'12px 28px'}} onClick={()=>saveCourse(true)} disabled={saving}>{saving?'Saving...':'Publish 🚀'}</button><button style={{...B.btn('ghost'),padding:'12px 28px'}} onClick={()=>saveCourse(false)} disabled={saving}>{saving?'Saving...':'Save Draft'}</button><button style={{...B.btn('ghost'),padding:'12px 20px'}} onClick={()=>{setTab('dashboard');setEditingCourse(null);}}>Cancel</button></div></div>)}</div></div>);}
